### ISSUE TITLE
录音权限还要在6.0做适配

### ISSUE THREAD

**Issue by txfyteen** [CPPAlien/ChatKeyboard#1]
使用的是N5的，6.0上直接闪退了，因为录音权限的问题。

**Comment by jiezili** [comment]
这个是需要自己做适配的哟

**Comment by CPPAlien** [comment]
已经在 1.0.7 版本中作出修改，RecordingAction中增加一个  PERMISSION_NOT_GRANTED  的动作，未赋权限时会返回，而不会奔溃，此时你可以选择请求权限
