### ISSUE TITLE
toolbar导致的问题

### ISSUE THREAD

**Issue by pye52** [CPPAlien/ChatKeyboard#3]
在界面上添加toolbar之后，autoview就会比键盘高出一截
而根布局用linearlayout的话就没问题了
但是RecordingLayout要显示在界面中央的话又只能用relativelayout…

**Comment by CPPAlien** [comment]
目前查到原因是因为使用layout _below等原因会造成autoview高度计算错误，可以暂且使用marginTop来规避，关于这个问题在进一步调查中

**Comment by pye52** [comment]
好的，感谢回复~不知道有没有继续维护更新的计划呢？

**Comment by CPPAlien** [comment]
有的
